// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sioyhdfiqkophyrkefjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpb3loZGZpcWtvcGh5cmtlZmprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTI4MjQsImV4cCI6MjA2MDEyODgyNH0.4NmXSIBH4er6uB4SMpP1uHYTqpxqWcd0-1NWTqiortY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);