// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glzwlfdicdugretdfsqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsendsZmRpY2R1Z3JldGRmc3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODYwNDIsImV4cCI6MjA2MDE2MjA0Mn0.J3LOi0Yqbqo3Qg_15dWyz_dny6IkhZvluP_JzGpFjFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);